### ISSUE TITLE
Not working in HOOBS

### ISSUE THREAD

**Issue by mikeyis** [ronniepettersson/homebridge-remootio#6]
When installing the plugin in both V3 and V4 of HOOBS, it comes up with an error and crashes the bridge.

`26/9/21, 7:17:51 pm TypeError: this.config.devices is not iterable
    at RemootioPlatform.discoverAndSyncAccessories (/hoobs/node_modules/homebridge-remootio/dist/platform.js:59:42)
    at API.<anonymous> (/hoobs/node_modules/homebridge-remootio/dist/platform.js:28:18)
    at API.emit (events.js:322:22)
    at Server.run (/usr/src/hoobs/bridge/server.js:104:18)
    at module.exports (/usr/src/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/src/hoobs/bin/hoobs:63:81)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)`

`26/9/21, 7:17:40 pm  WARN notsup Unsupported engine for homebridge-remootio@1.2.5: wanted: {"homebridge":"^1.1.0","node":">=12.18.3"} (current: {"node":"12.16.2","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: homebridge-remootio@1.2.5
26/9/21, 7:17:40 pm 
26/9/21, 7:17:40 pm + homebridge-remootio@1.2.5
updated 1 package in 0.621s
26/9/21, 7:17:40 pm 
2 packages are looking for funding
  run `npm fund` for details
26/9/21, 7:17:40 pm Plugin "homebridge-remootio" installed.
26/9/21, 7:17:40 pm Got SIGINT, shutting down Bridge...`

**Comment by ronniepettersson** [comment]
This plugin has not been tested with HOOBS (yet).  

I noticed that the install script (https://github.com/hoobs-org/HOOBS/blob/main/install.sh )for HOOBS V4 targets the following node and npm versions:
    NODE_TARGET="14.16.0"
    NPM_TARGET="6.14.5"

Your error log suggests that your node version is not compatible. Maybe try to update node/npm?

**Comment by mikeyis** [comment]
I'll have a crack now :)

**Comment by mikeyis** [comment]
Nah no love. Switched over to using Homebridge and works tho :) I'll contact HOOBS, as they have it listed as a certified plugin :)
